import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/desktoptwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/desktopone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/desktopfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/desktopthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/desktopfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/desktopsix" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopSix
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/desktopeight" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopEight
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/desktopseven" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopSeven
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
